{% set name = "python-u2flib-server" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b9044db13fe24abc7a07c2bdb4b7bb541ca275702f43ecbd0d9641c28bcc226

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - u2flib_server

about:
  home: https://pypi.org/project/python-u2flib-server/
  summary: python-u2flib-server, functionality for working with the server side aspects of the U2F protocol.
  license: BSD-2-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
